name: pytest-rts

on: [push]

jobs:
  check:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit message
        uses: adityaa30/check-commit@master
  
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Lint and test
        run: tox -e py -- --exitfirst
